name: stocks
channels:
  - anaconda
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - fire
  - black
  - gcsfs
  - cloudpathlib
  - google-cloud-pubsub
  - jupyterlab
  - pylint

  - pip:
    - discord-webhook
