name: stocks
channels:
  - anaconda
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - fire
  - black
  - gcsfs
  - pandas-gbq
  - cloudpathlib
  - google-cloud-pubsub
  - google-cloud-bigquery
  - pylint
  - google-auth
  - pytest
  - matplotlib
  - jupyterlab
  - pip

  - pip:
    - discord-webhook
    - yahooquery
    - dbt-core
    - dbt-bigquery
