name: stocks
channels:
  - anaconda
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - fire
  - black
  - gcsfs
  - pandas-gbq
  - cloudpathlib
  - google-cloud-pubsub
  - jupyterlab
  - pylint
  - google-auth

  - pip:
    - discord-webhook
    - yahooquery
