stocks:
  target: stocks
  outputs:
    stocks:
      schema: stocks
      type: bigquery
      method: oauth
      project: '{{ env_var("PROJECT_ID", "none") }}'
      threads: 1
      timeout_seconds: 300
      location: US
      priority: interactive