version: 2

sources:
  - name: stocks
    database: '{{ env_var("PROJECT_ID", "none") }}'
    schema: stocks  
    tables:
      - name: listed_companies
      - name: prices_hourly
      - name: prices_minutely
      - name: simulated_trades
