version: 2

sources:
  - name: stocks
    database: '{{ env_var("TF_VAR_project_id", "none") }}'
    schema: stocks  
    tables:
      - name: listed_companies
      - name: prices_hourly
      - name: prices_minutely
