name: CI
run-name: CI triggered by ${{ github.event_name }} from ${{ github.actor }}

on:
  push:
    branches: 
      - "master"
  pull_request:
    branches: [master]

jobs:
  CI:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup conda env
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          use-mamba: true

          activate-environment: stocks
          environment-file: environment.yml

      - name: Check formatting
        run: black . --check

      - name: Run tests
        run: pytest src/messenger/ && pytest src/stock_scraper/
