
name: Run DBT

on:
  schedule:
    - cron:  "45 7 * * 1-5"
  workflow_dispatch:
env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}

jobs:
  schedule:
    name: scheduled_run
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@master

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.CREDENTIALS }}'

      - uses: actions/setup-python@v1
        with:
          python-version: "3.7.x"

      - name: Install dependencies
        run: |
          pip install dbt-core
          pip install dbt-bigquery
      
      - name: Run dbt
        run: cd src/warehouse && dbt run
